name: Leetcoding every day

on:
  schedule:
  - cron: "58 15 * * *"
  workflow_dispatch:


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install requirements
      run: pip install requests

    - name: Run Scripts
      run: python ./LeetCoding/leetcoding.py
